#!/usr/bin/env bash

set -euxo pipefail

# Settings.
EMACS_HOME=~/.emacs.d


# Purge previous configuration.
if [ -d "${EMACS_HOME}" ]; then
    for i in eshell lisp site-lisp snippets; do
        rm -rf "${EMACS_HOME:?}/${i}" || true
    done

    rm "${EMACS_HOME}"/{early-init.el,init.el} || true
else
    mkdir "${EMACS_HOME}"
fi


# Install new configuration.
cp early-init.el init.el "${EMACS_HOME}"

for i in lisp site-lisp; do
    cp -r "${i}" "${EMACS_HOME}"
done

cp -r eshell "${EMACS_HOME}/etc/"
cp -r snippets "${EMACS_HOME}/etc/yasnippet/"
